/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_Cipher */

#ifndef _Included_JNI_Cipher
#define _Included_JNI_Cipher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_Cipher
 * Method:    SGX_Cipher_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNI_1Cipher_SGX_1Cipher_1init
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Cipher
 * Method:    SGX_Cipher_update
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNI_1Cipher_SGX_1Cipher_1update
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Cipher
 * Method:    SGX_Cipher_dofinal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNI_1Cipher_SGX_1Cipher_1dofinal
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
