/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_KeyGenerator */

#ifndef _Included_JNI_KeyGenerator
#define _Included_JNI_KeyGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_KeyGenerator
 * Method:    SGX_KeyGenerator_init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JNI_1KeyGenerator_SGX_1KeyGenerator_1init
  (JNIEnv *, jobject, jint);

/*
 * Class:     JNI_KeyGenerator
 * Method:    SGX_KeyGenerator_generateKey
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JNI_1KeyGenerator_SGX_1KeyGenerator_1generateKey
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
