/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_KeyGenerator */

#ifndef _Included_JNI_KeyGenerator
#define _Included_JNI_KeyGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_KeyGenerator
 * Method:    SGX_KeyGenerator
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_1KeyGenerator_SGX_1KeyGenerator
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
